/**
 * Plan de cierre 2026 normalizado desde
 * Epical_Estrategia_Cierre_2026.docx y .context/mapa_objetivos_acciones_2026.md.
 *
 * Este archivo es una fuente de datos inicial: no contiene avances actuales.
 * Los porcentajes quedan en null y todos los objetivos/acciones comienzan en
 * planned para que el seguimiento pueda conectarse luego a persistencia.
 */

export type ObjectiveLevel = "company" | "area" | "person";
export type ObjectiveStatus = "planned";
export type ActionStatus = "planned";
export type PlanMonth = "septiembre" | "octubre" | "noviembre" | "diciembre";

export interface Objective2026 {
  slug: string;
  level: ObjectiveLevel;
  areaKey: string;
  title: string;
  metric: string;
  target: string;
  ownerName: string;
  status: ObjectiveStatus;
  progressPercent: null;
}

export interface Account2026 {
  slug: string;
  name: string;
}

export interface Action2026 {
  slug: string;
  objectiveSlug: string | null;
  accountSlug: string | null;
  title: string;
  description?: string;
  month: PlanMonth;
  weekLabel: string;
  weekStart: string;
  dueDate: string | null;
  focus: string;
  accountableOwnerName: string;
  supportingOwnerNames: string[];
  status: ActionStatus;
  dependencySlugs: string[];
  sortOrder: number;
}

export interface ObjectivePlan2026 {
  objectives: Objective2026[];
  accounts: Account2026[];
  actions: Action2026[];
}

const RAW_OBJECTIVE_PLAN_2026: ObjectivePlan2026 = {
  objectives: [
    // Empresa — norte anual y del cuatrimestre.
    {
      slug: "company-annual-revenue",
      level: "company",
      areaKey: "company",
      title: "Facturación 2026 en o por encima del escenario base",
      metric: "Facturación anual",
      target: "USD 655K; piso aceptable USD 610K; escenario superior USD 710K, al 31 de diciembre",
      ownerName: "Tomás",
      status: "planned",
      progressPercent: null,
    },
    {
      slug: "company-new-recurring-signed",
      level: "company",
      areaKey: "company",
      title: "Facturación mensual nueva, recurrente y firmada",
      metric: "Facturación mensual nueva recurrente firmada",
      target: "Al menos USD 10.000 por mes al 30 de noviembre",
      ownerName: "Vicky",
      status: "planned",
      progressPercent: null,
    },
    {
      slug: "company-new-monthly-fee",
      level: "company",
      areaKey: "company",
      title: "Al menos un fee mensual nuevo firmado y facturando",
      metric: "Contrato firmado y primera factura emitida",
      target: "Al menos 1 fee mensual nuevo al 31 de diciembre",
      ownerName: "Vicky",
      status: "planned",
      progressPercent: null,
    },
    {
      slug: "company-cash-runway",
      level: "company",
      areaKey: "company",
      title: "Caja proyectada a 13 semanas protegida",
      metric: "Semanas de caja proyectada",
      target: "Nunca por debajo de un mes de sueldos; contingencia Oxean acordada por escrito",
      ownerName: "Vicky",
      status: "planned",
      progressPercent: null,
    },
    {
      slug: "company-proposal-margin",
      level: "company",
      areaKey: "company",
      title: "Margen mínimo definido para toda propuesta nueva",
      metric: "Margen por propuesta",
      target: "Piso definido con Tonga; ninguna excepción sin firma de Tomás",
      ownerName: "Vicky",
      status: "planned",
      progressPercent: null,
    },
    {
      slug: "company-expansion-fee",
      level: "company",
      areaKey: "company",
      title: "Cerrar al menos una expansión con fee mensual",
      metric: "Contratos de expansión firmados",
      target: "Al menos 1 contrato firmado al 30 de noviembre; candidatas BID, PedidosYa o Kimberly ampliada",
      ownerName: "Vicky",
      status: "planned",
      progressPercent: null,
    },
    {
      slug: "company-new-business-proposals",
      level: "company",
      areaKey: "company",
      title: "Nuevos negocios fuera de la cartera recurrente",
      metric: "Propuestas presentadas y firmadas",
      target: "2 propuestas presentadas y al menos 1 firmada durante el cuatrimestre",
      ownerName: "Tomás",
      status: "planned",
      progressPercent: null,
    },
    {
      slug: "company-bcra-decision",
      level: "company",
      areaKey: "company",
      title: "BCRA llevado a decisión de contrato gestionado",
      metric: "Piloto entregado y reunión de decisión realizada",
      target: "Decisión tomada al 30 de noviembre: contrato firmado o reclasificación a oportunidades 2027",
      ownerName: "Tomás",
      status: "planned",
      progressPercent: null,
    },
    {
      slug: "company-warner-mexico",
      level: "company",
      areaKey: "company",
      title: "Abrir Anticipación Estratégica con Warner México",
      metric: "Reunión realizada y propuesta enviada",
      target: "Conversación abierta al 31 de octubre, separada de la renovación de abril",
      ownerName: "Tomás",
      status: "planned",
      progressPercent: null,
    },
    {
      slug: "company-uber-reputational",
      level: "company",
      areaKey: "company",
      title: "Abrir la puerta Reputacional en Uber",
      metric: "Reunión con Asuntos Públicos Chile",
      target: "Reunión realizada al 30 de noviembre",
      ownerName: "Tomás",
      status: "planned",
      progressPercent: null,
    },
    {
      slug: "company-triggers-product",
      level: "company",
      areaKey: "company",
      title: "Servicio de triggers definido",
      metric: "Documento de producto, entregable, precio y plan operativo",
      target: "Producto y precio aprobados al 30 de septiembre",
      ownerName: "Tomás",
      status: "planned",
      progressPercent: null,
    },
    {
      slug: "company-kimberly-renewal-price",
      level: "company",
      areaKey: "company",
      title: "Renovar Kimberly-Clark con precio corregido",
      metric: "Contrato de renovación firmado; Insights separado como anexo",
      target: "Renovación firmada al 21 de diciembre",
      ownerName: "Vicky",
      status: "planned",
      progressPercent: null,
    },
    {
      slug: "company-coelsa-retention",
      level: "company",
      areaKey: "company",
      title: "Retener COELSA con continuidad para 2027",
      metric: "Confirmación escrita de continuidad",
      target: "Renovación o extensión confirmada al 30 de noviembre",
      ownerName: "Vicky",
      status: "planned",
      progressPercent: null,
    },
    {
      slug: "company-on-time-delivery",
      level: "company",
      areaKey: "company",
      title: "Operación lista para absorber lo que se firme",
      metric: "Entregables recurrentes a tiempo",
      target: "100% de entregables recurrentes a tiempo durante todo el cuatrimestre",
      ownerName: "Vicky",
      status: "planned",
      progressPercent: null,
    },
    {
      slug: "company-client-alerts",
      level: "company",
      areaKey: "company",
      title: "Alertas de clientes reportadas rápidamente",
      metric: "Alertas detectadas reportadas en menos de 48 horas",
      target: "100% de las alertas de cliente reportadas en <48h",
      ownerName: "Vicky",
      status: "planned",
      progressPercent: null,
    },
    {
      slug: "company-second-interlocutor",
      level: "company",
      areaKey: "company",
      title: "Segundo interlocutor activo en cuentas clave",
      metric: "Cuentas clave con al menos dos interlocutores",
      target: "4 de 5 cuentas clave con segundo contacto activo",
      ownerName: "Vicky",
      status: "planned",
      progressPercent: null,
    },
    {
      slug: "company-2027-opportunities",
      level: "company",
      areaKey: "company",
      title: "Cartera activa de oportunidades para 2027",
      metric: "Propuestas activas con presupuesto y fecha de decisión",
      target: "Al menos 3 propuestas activas para Q1 2027 al 31 de diciembre",
      ownerName: "Tomás",
      status: "planned",
      progressPercent: null,
    },
    {
      slug: "company-alert-subscriptions",
      level: "company",
      areaKey: "company",
      title: "Suscripciones de alertas y triggers firmadas",
      metric: "Contratos de suscripción firmados",
      target: "3 suscripciones firmadas al 31 de diciembre; candidatas Kimberly, COELSA y BCRA",
      ownerName: "Vicky",
      status: "planned",
      progressPercent: null,
    },
    {
      slug: "company-own-products-baseline",
      level: "company",
      areaKey: "company",
      title: "Medir la línea base de productos propios",
      metric: "Facturación de productos propios sobre el total",
      target: "Línea base definida al 30 de septiembre; objetivo 2027 de 10–13%",
      ownerName: "Tomás",
      status: "planned",
      progressPercent: null,
    },
    {
      slug: "company-month-sep-open-mesas",
      level: "company",
      areaKey: "company",
      title: "Septiembre: abrir todas las mesas",
      metric: "Expansiones abiertas y triggers con precio",
      target: "Warner, Kimberly y PedidosYa abiertos; BID con fecha de decisión; triggers con precio al 30 de septiembre",
      ownerName: "Tomás",
      status: "planned",
      progressPercent: null,
    },
    {
      slug: "company-month-oct-advance",
      level: "company",
      areaKey: "company",
      title: "Octubre: avanzar y presionar",
      metric: "Negociaciones activas y contactos de Frontera",
      target: "Kimberly en negociación concreta, PedidosYa cerca de firma, Warner enviada, Uber reunido y Frontera convertida en contactos",
      ownerName: "Tomás",
      status: "planned",
      progressPercent: null,
    },
    {
      slug: "company-month-nov-close",
      level: "company",
      areaKey: "company",
      title: "Noviembre: cerrar",
      metric: "Expansión firmada y oportunidades 2027",
      target: "Al menos una expansión firmada; BID/BCRA resueltos; primer borrador de oportunidades 2027 completo al 30 de noviembre",
      ownerName: "Tomás",
      status: "planned",
      progressPercent: null,
    },
    {
      slug: "company-month-dec-renew",
      level: "company",
      areaKey: "company",
      title: "Diciembre: renovar y dejar servida la mesa 2027",
      metric: "Renovación, facturación, revisión anual y enero agendado",
      target: "Kimberly firmada; todo lo vendido facturando; revisión anual hecha; primera reunión de enero agendada",
      ownerName: "Tomás",
      status: "planned",
      progressPercent: null,
    },

    // Áreas — Sales, Marketing, Operación y Producto/Estrategia.
    {
      slug: "area-sales-ideal-accounts",
      level: "area",
      areaKey: "sales",
      title: "Cerrar la lista de clientes ideales",
      metric: "Cuentas y contactos calificados",
      target: "60 cuentas objetivo LATAM y 120 contactos calificados al 15 de septiembre",
      ownerName: "Sil",
      status: "planned",
      progressPercent: null,
    },
    {
      slug: "area-sales-weekly-cadence",
      level: "area",
      areaKey: "sales",
      title: "Sostener la cadencia semanal 25/5/1",
      metric: "Contactos nuevos, conversaciones abiertas y reuniones",
      target: "25 contactos nuevos, 5 conversaciones abiertas y 1 reunión agendada cada semana",
      ownerName: "Sil",
      status: "planned",
      progressPercent: null,
    },
    {
      slug: "area-sales-vertical-sequences",
      level: "area",
      areaKey: "sales",
      title: "Construir secuencias por vertical",
      metric: "Secuencias aprobadas",
      target: "3 secuencias: consumo masivo, farma y fintech, al 19 de septiembre",
      ownerName: "Sil",
      status: "planned",
      progressPercent: null,
    },
    {
      slug: "area-sales-follow-up-lane",
      level: "area",
      areaKey: "sales",
      title: "Operar la pista de seguimiento largo",
      metric: "Contactos interesados con último contacto reciente",
      target: "100% de interesados sin presupuesto/fecha con seguimiento quincenal y último contacto <15 días",
      ownerName: "Sil",
      status: "planned",
      progressPercent: null,
    },
    {
      slug: "area-sales-response-time",
      level: "area",
      areaKey: "sales",
      title: "Responder interesados en menos de 48 horas",
      metric: "Tiempo de respuesta",
      target: "100% de contactos interesados del Radar y LinkedIn contactados en <48h",
      ownerName: "Sil",
      status: "planned",
      progressPercent: null,
    },
    {
      slug: "area-sales-loss-reasons",
      level: "area",
      areaKey: "sales",
      title: "Registrar motivos de oportunidades perdidas",
      metric: "Casos con motivo registrado",
      target: "Tabla con al menos 10 casos al 30 de noviembre",
      ownerName: "Sil",
      status: "planned",
      progressPercent: null,
    },
    {
      slug: "area-sales-qualified-meetings",
      level: "area",
      areaKey: "sales",
      title: "Entregar reuniones calificadas",
      metric: "Reuniones calificadas entregadas a Vicky/Tomás",
      target: "Al menos 8 en el cuatrimestre, 2 por mes, al 31 de diciembre",
      ownerName: "Sil",
      status: "planned",
      progressPercent: null,
    },
    {
      slug: "area-marketing-google-ads",
      level: "area",
      areaKey: "marketing",
      title: "Lanzar Google Ads sobre el Radar",
      metric: "Campaña activa y costo por contacto",
      target: "Presupuesto y costo por contacto objetivo definidos antes de activar; campaña activa al 19 de septiembre",
      ownerName: "Santi",
      status: "planned",
      progressPercent: null,
    },
    {
      slug: "area-marketing-newsletters",
      level: "area",
      areaKey: "marketing",
      title: "Enviar newsletter quincenal",
      metric: "Ediciones con apertura y clic medidos",
      target: "6 ediciones durante el cuatrimestre, desde el 15 de septiembre",
      ownerName: "Santi",
      status: "planned",
      progressPercent: null,
    },
    {
      slug: "area-marketing-linkedin",
      level: "area",
      areaKey: "marketing",
      title: "Sostener la página de LinkedIn",
      metric: "Publicaciones mensuales",
      target: "12 publicaciones por mes, con seguidores e interacción medidos",
      ownerName: "Santi",
      status: "planned",
      progressPercent: null,
    },
    {
      slug: "area-marketing-vertical-pages",
      level: "area",
      areaKey: "marketing",
      title: "Publicar páginas web por vertical",
      metric: "Páginas con formulario",
      target: "3 páginas publicadas: farma, bebidas/consumo masivo y fintech, al 31 de octubre",
      ownerName: "Santi",
      status: "planned",
      progressPercent: null,
    },
    {
      slug: "area-marketing-cases",
      level: "area",
      areaKey: "marketing",
      title: "Convertir evidencia en casos escritos",
      metric: "Casos de una página aprobados",
      target: "Warner Insights, piloto PepsiCo y piloto BCRA aprobados al 31 de octubre",
      ownerName: "Santi",
      status: "planned",
      progressPercent: null,
    },
    {
      slug: "area-marketing-frontier-content",
      level: "area",
      areaKey: "marketing",
      title: "Publicar contenido de Conversaciones de Frontera",
      metric: "Pieza publicada en LinkedIn y newsletter",
      target: "Contenido publicado antes del 6 de noviembre",
      ownerName: "Santi",
      status: "planned",
      progressPercent: null,
    },
    {
      slug: "area-marketing-qualified-leads",
      level: "area",
      areaKey: "marketing",
      title: "Entregar contactos con interés real a Sales",
      metric: "Contactos interesados entregados",
      target: "Al menos 15 en el cuatrimestre, 5 por mes desde octubre",
      ownerName: "Santi",
      status: "planned",
      progressPercent: null,
    },
    {
      slug: "area-operations-kimberly-expansion",
      level: "area",
      areaKey: "operations",
      title: "Separar renovación y expansión de Kimberly",
      metric: "Renovación con precio corregido y anexo separado",
      target: "Renovación base y Consumer Insights negociados como conversaciones separadas; firma al 21 de diciembre",
      ownerName: "Vicky",
      status: "planned",
      progressPercent: null,
    },
    {
      slug: "area-operations-pedidosya-recurring",
      level: "area",
      areaKey: "operations",
      title: "Convertir PedidosYa a fee recurrente",
      metric: "Propuesta y acuerdo de recurrencia",
      target: "Propuesta enviada al 19 de septiembre y acuerdo verbal o firma al 31 de octubre",
      ownerName: "Vicky",
      status: "planned",
      progressPercent: null,
    },
    {
      slug: "area-operations-warner-sequence",
      level: "area",
      areaKey: "operations",
      title: "Ordenar la secuencia de expansión Warner",
      metric: "Hilos con interlocutor y próximo paso",
      target: "Anexo de créditos, Piracy y Anticipación Estratégica separados y comunicados",
      ownerName: "Vicky",
      status: "planned",
      progressPercent: null,
    },
    {
      slug: "area-operations-coelsa-retention",
      level: "area",
      areaKey: "operations",
      title: "Retener COELSA antes de expandir",
      metric: "Reunión de retención y continuidad escrita",
      target: "Riesgo conversado al 19 de septiembre y continuidad 2027 confirmada al 30 de noviembre",
      ownerName: "Vicky",
      status: "planned",
      progressPercent: null,
    },
    {
      slug: "area-operations-expansion-meetings",
      level: "area",
      areaKey: "operations",
      title: "Realizar reuniones de expansión",
      metric: "Reuniones realizadas",
      target: "Al menos 4 durante el cuatrimestre: Warner, Kimberly, Uber y PedidosYa",
      ownerName: "Vicky",
      status: "planned",
      progressPercent: null,
    },
    {
      slug: "area-operations-on-time-delivery",
      level: "area",
      areaKey: "operations",
      title: "Mantener cero atrasos recurrentes",
      metric: "Entregas recurrentes a tiempo",
      target: "100% durante septiembre–diciembre",
      ownerName: "Vicky",
      status: "planned",
      progressPercent: null,
    },
    {
      slug: "area-operations-licenses",
      level: "area",
      areaKey: "operations",
      title: "Resolver licencias y transición de infraestructura",
      metric: "Decisiones de licencias y responsabilidades reasignadas",
      target: "Auditoría cerrada en septiembre; transición de datos antes del piloto BCRA",
      ownerName: "Acha",
      status: "planned",
      progressPercent: null,
    },
    {
      slug: "area-operations-process",
      level: "area",
      areaKey: "operations",
      title: "Automatizar o mejorar un proceso",
      metric: "Proceso documentado",
      target: "Al menos 1 proceso automatizado o mejorado y documentado antes del 15 de diciembre",
      ownerName: "Acha",
      status: "planned",
      progressPercent: null,
    },
    {
      slug: "area-operations-cash-billing",
      level: "area",
      areaKey: "operations",
      title: "Controlar caja, anticipos, margen y facturación",
      metric: "Caja a 13 semanas, anticipos, margen y primera factura",
      target: "Caja nunca bajo un mes de sueldos; todo contrato nuevo con anticipo y lo firmado facturando",
      ownerName: "Vicky",
      status: "planned",
      progressPercent: null,
    },
    {
      slug: "area-product-triggers",
      level: "area",
      areaKey: "product-strategy",
      title: "Empaquetar triggers como producto",
      metric: "Producto, entregable, precio y plan operativo aprobados",
      target: "Definición lista al 30 de septiembre",
      ownerName: "Tomás",
      status: "planned",
      progressPercent: null,
    },
    {
      slug: "area-product-radar-cuts",
      level: "area",
      areaKey: "product-strategy",
      title: "Vender cortes del Radar por industria",
      metric: "Corte con precio y ficha ofrecido",
      target: "Primer corte pago de bebidas/consumo masivo ofrecido a los cuatro contactos interesados al 30 de septiembre",
      ownerName: "Tomás",
      status: "planned",
      progressPercent: null,
    },
    {
      slug: "area-product-paid-diagnosis",
      level: "area",
      areaKey: "product-strategy",
      title: "Reemplazar demo gratis por diagnóstico pago",
      metric: "Política de diagnóstico y próxima propuesta",
      target: "Política definida y próxima demo de Roche o Mercedes presentada con precio al 30 de septiembre",
      ownerName: "Tomás",
      status: "planned",
      progressPercent: null,
    },
    {
      slug: "area-product-alerts",
      level: "area",
      areaKey: "product-strategy",
      title: "Definir alertas 24/7 como producto",
      metric: "Ficha de producto con precio",
      target: "Producto seguro con precio propio definido al 15 de octubre",
      ownerName: "Tomás",
      status: "planned",
      progressPercent: null,
    },
    {
      slug: "area-product-dashboard",
      level: "area",
      areaKey: "product-strategy",
      title: "Ofrecer dashboard agéntico como complemento",
      metric: "Precio de complemento ofrecido en renovación",
      target: "Precio definido y ofrecido en la renovación de Kimberly al 31 de octubre",
      ownerName: "Tomás",
      status: "planned",
      progressPercent: null,
    },
    {
      slug: "area-product-agency-channel",
      level: "area",
      areaKey: "product-strategy",
      title: "Abrir canal de agencias",
      metric: "Agencias contactadas con propuesta de alianza",
      target: "2 agencias adicionales contactadas al 30 de noviembre, sobre 3 agencias objetivo",
      ownerName: "Vicky",
      status: "planned",
      progressPercent: null,
    },
    {
      slug: "area-product-mind-pilot",
      level: "area",
      areaKey: "product-strategy",
      title: "Cotizar Mind sin desarrollarlo para terceros",
      metric: "Licencia piloto cotizada y decisión registrada",
      target: "Cotización enviada sin compromiso de desarrollo al 30 de septiembre",
      ownerName: "Vicky",
      status: "planned",
      progressPercent: null,
    },
    {
      slug: "area-product-sme-2027",
      level: "area",
      areaKey: "product-strategy",
      title: "Documentar demanda de producto PYME para 2027",
      metric: "Casos de demanda documentados",
      target: "Al menos 3 casos al cierre del año; sin construcción inmediata",
      ownerName: "Vicky",
      status: "planned",
      progressPercent: null,
    },

    // Personas — resultados y hábitos explícitos del documento.
    {
      slug: "person-tomas-annual-billing",
      level: "person",
      areaKey: "ceo",
      title: "Responder por la facturación anual proyectada",
      metric: "Facturación anual y resultado de cierre",
      target: "USD 655K base, con piso USD 610K, al 31 de diciembre",
      ownerName: "Tomás",
      status: "planned",
      progressPercent: null,
    },
    {
      slug: "person-tomas-2027-pipeline",
      level: "person",
      areaKey: "ceo",
      title: "Construir la cartera de oportunidades 2027",
      metric: "Propuestas activas con presupuesto y fecha",
      target: "Al menos 3 propuestas activas para Q1 2027 y primera reunión de enero agendada",
      ownerName: "Tomás",
      status: "planned",
      progressPercent: null,
    },
    {
      slug: "person-tomas-strategic-opportunities",
      level: "person",
      areaKey: "ceo",
      title: "Liderar BCRA, PepsiCo, Warner México, Uber Reputacional y nuevo negocio",
      metric: "Oportunidades estratégicas con próximo paso fechado",
      target: "Piloto BCRA, propuesta PepsiCo, reunión/propuesta Warner México y reunión Uber resueltos según sus fechas",
      ownerName: "Tomás",
      status: "planned",
      progressPercent: null,
    },
    {
      slug: "person-tomas-product-pricing",
      level: "person",
      areaKey: "ceo",
      title: "Definir producto y precio de los activos propios",
      metric: "Fichas de producto aprobadas",
      target: "Triggers, cortes del Radar, diagnóstico pago, alertas y dashboard con precio y siguiente acción",
      ownerName: "Tomás",
      status: "planned",
      progressPercent: null,
    },
    {
      slug: "person-tomas-radar-calls",
      level: "person",
      areaKey: "ceo",
      title: "Llamar personalmente a los cuatro contactos grandes del Radar",
      metric: "Llamadas a CCU, Nestlé, Mondelez y Mercado Libre",
      target: "4 llamadas y reunión o no explícito de cada cuenta al 19 de septiembre",
      ownerName: "Tomás",
      status: "planned",
      progressPercent: null,
    },
    {
      slug: "person-tomas-discovery",
      level: "person",
      areaKey: "ceo",
      title: "Hacer conversaciones de descubrimiento con clientes actuales",
      metric: "Conversaciones con nota de hallazgos",
      target: "5 conversaciones de Tomás y 5 de Vicky en 30 días, al 30 de septiembre",
      ownerName: "Tomás",
      status: "planned",
      progressPercent: null,
    },
    {
      slug: "person-tomas-sales-focus",
      level: "person",
      areaKey: "ceo",
      title: "Proteger el foco comercial del CEO",
      metric: "Agenda bloqueada y prioridades semanales",
      target: "50% de agenda bloqueada para ventas, martes y jueves sin reuniones internas, 3 prioridades por semana hasta el 30 de noviembre",
      ownerName: "Tomás",
      status: "planned",
      progressPercent: null,
    },
    {
      slug: "person-tomas-no-build-focus",
      level: "person",
      areaKey: "ceo",
      title: "Preservar el foco y la lista de no-hacer",
      metric: "Iniciativas fuera de foco no iniciadas",
      target: "No desarrollar Mind para terceros, PYME, GeaIQ ni productos fuera de triggers/fichas hasta el 30 de noviembre",
      ownerName: "Tomás",
      status: "planned",
      progressPercent: null,
    },
    {
      slug: "person-vicky-existing-account-closures",
      level: "person",
      areaKey: "coo",
      title: "Liderar cierres sobre relaciones existentes",
      metric: "Kimberly, PedidosYa, COELSA y expansiones con siguiente paso",
      target: "Cerrar renovación Kimberly, continuidad COELSA, recurrencia PedidosYa y al menos una expansión",
      ownerName: "Vicky",
      status: "planned",
      progressPercent: null,
    },
    {
      slug: "person-vicky-coordination",
      level: "person",
      areaKey: "coo",
      title: "Coordinar Sales, PMs y Acha",
      metric: "Objetivos bajados y prioridades aprobadas",
      target: "Sales, PMs y Acha trabajan con dueño, acción y fecha en el ritual comercial semanal",
      ownerName: "Vicky",
      status: "planned",
      progressPercent: null,
    },
    {
      slug: "person-vicky-cash-margin-billing",
      level: "person",
      areaKey: "coo",
      title: "Controlar caja, anticipos, margen y facturación",
      metric: "Caja, anticipo, margen y facturas",
      target: "Caja a 13 semanas protegida; contratos con anticipo; margen aprobado y primera factura emitida",
      ownerName: "Vicky",
      status: "planned",
      progressPercent: null,
    },
    {
      slug: "person-vicky-operational-quality",
      level: "person",
      areaKey: "coo",
      title: "Garantizar calidad operativa y respuesta",
      metric: "Atrasos, alertas y segundo interlocutor",
      target: "Cero atrasos recurrentes, alertas <48h y segundo interlocutor en 4 de 5 cuentas clave",
      ownerName: "Vicky",
      status: "planned",
      progressPercent: null,
    },
    {
      slug: "person-vicky-expansion-and-discovery",
      level: "person",
      areaKey: "coo",
      title: "Liderar expansiones y descubrir oportunidades del equipo",
      metric: "Reuniones de expansión, descubrimiento y oportunidades detectadas",
      target: "4 reuniones de expansión, 5 conversaciones de descubrimiento y al menos 1 oportunidad originada por el equipo",
      ownerName: "Vicky",
      status: "planned",
      progressPercent: null,
    },
    {
      slug: "person-vicky-team-feedback",
      level: "person",
      areaKey: "coo",
      title: "Completar los 1:1 de devolución",
      metric: "Personas con 1:1 y conclusiones",
      target: "100% del equipo al 15 de diciembre",
      ownerName: "Vicky",
      status: "planned",
      progressPercent: null,
    },
    {
      slug: "person-sil-target-list",
      level: "person",
      areaKey: "sales",
      title: "Construir lista de cuentas y contactos",
      metric: "Cuentas y contactos",
      target: "60 cuentas y 120 contactos calificados",
      ownerName: "Sil",
      status: "planned",
      progressPercent: null,
    },
    {
      slug: "person-sil-prospecting-cadence",
      level: "person",
      areaKey: "sales",
      title: "Ejecutar cadencia de prospección",
      metric: "Cadencia 25/5/1",
      target: "25 contactos nuevos, 5 conversaciones y 1 reunión por semana",
      ownerName: "Sil",
      status: "planned",
      progressPercent: null,
    },
    {
      slug: "person-sil-vertical-messaging",
      level: "person",
      areaKey: "sales",
      title: "Preparar tres secuencias por vertical",
      metric: "Secuencias aprobadas",
      target: "Consumo masivo, farma y fintech al 19 de septiembre",
      ownerName: "Sil",
      status: "planned",
      progressPercent: null,
    },
    {
      slug: "person-sil-follow-up-and-response",
      level: "person",
      areaKey: "sales",
      title: "Sostener seguimiento y respuesta de interesados",
      metric: "Antigüedad de último contacto y SLA",
      target: "Seguimiento <15 días y respuesta <48h a todos los interesados",
      ownerName: "Sil",
      status: "planned",
      progressPercent: null,
    },
    {
      slug: "person-sil-meetings-and-losses",
      level: "person",
      areaKey: "sales",
      title: "Entregar reuniones y estadística de pérdidas",
      metric: "Reuniones calificadas y motivos de pérdida",
      target: "8 reuniones calificadas en el cuatrimestre y al menos 10 motivos registrados al 30 de noviembre",
      ownerName: "Sil",
      status: "planned",
      progressPercent: null,
    },
    {
      slug: "person-santi-demand-channels",
      level: "person",
      areaKey: "marketing",
      title: "Activar Google Ads, newsletter, LinkedIn y web",
      metric: "Canales activos y métricas de demanda",
      target: "Google Ads activo, 6 newsletters, 12 publicaciones mensuales y 3 páginas verticales",
      ownerName: "Santi",
      status: "planned",
      progressPercent: null,
    },
    {
      slug: "person-santi-cases-and-frontier",
      level: "person",
      areaKey: "marketing",
      title: "Producir casos y contenido de Frontera",
      metric: "Casos aprobados y contenido publicado",
      target: "3 casos escritos y contenido de Frontera publicado antes del 6 de noviembre",
      ownerName: "Santi",
      status: "planned",
      progressPercent: null,
    },
    {
      slug: "person-santi-qualified-leads",
      level: "person",
      areaKey: "marketing",
      title: "Entregar contactos interesados a Sales",
      metric: "Contactos con interés real entregados",
      target: "Al menos 15 durante el cuatrimestre, 5 por mes desde octubre",
      ownerName: "Santi",
      status: "planned",
      progressPercent: null,
    },
    {
      slug: "person-santi-marketing-board-pack",
      level: "person",
      areaKey: "marketing",
      title: "Reportar el tablero de marketing",
      metric: "Contactos, costo, suscriptores y tráfico",
      target: "Datos reportados en el board pack el último día hábil de cada mes",
      ownerName: "Santi",
      status: "planned",
      progressPercent: null,
    },
    {
      slug: "person-acha-license-audit",
      level: "person",
      areaKey: "processes-tools",
      title: "Auditar herramientas y licencias",
      metric: "Uso real contra costo y decisión",
      target: "Documento con baja o consolidación al 30 de septiembre",
      ownerName: "Acha",
      status: "planned",
      progressPercent: null,
    },
    {
      slug: "person-acha-infrastructure-transition",
      level: "person",
      areaKey: "processes-tools",
      title: "Completar la transición de infraestructura de datos",
      metric: "Responsabilidades reasignadas",
      target: "Transición documentada antes de la entrega del piloto BCRA",
      ownerName: "Acha",
      status: "planned",
      progressPercent: null,
    },
    {
      slug: "person-acha-radar-relaunch",
      level: "person",
      areaKey: "processes-tools",
      title: "Relanzar el Radar con medición",
      metric: "Destinatarios, medición, formato y dueño",
      target: "50 envíos con medición activa y próxima fecha del Radar publicada al 19 de septiembre",
      ownerName: "Acha",
      status: "planned",
      progressPercent: null,
    },
    {
      slug: "person-acha-process-improvement",
      level: "person",
      areaKey: "processes-tools",
      title: "Automatizar o mejorar y documentar un proceso",
      metric: "Proceso implementado y documentado",
      target: "Al menos uno antes del 15 de diciembre",
      ownerName: "Acha",
      status: "planned",
      progressPercent: null,
    },
    {
      slug: "person-pau-warner-mexico-access",
      level: "person",
      areaKey: "warner-team",
      title: "Gestionar el acceso a Warner México",
      metric: "Reunión de Anticipación Estratégica confirmada",
      target: "Reunión conseguida antes del 30 de septiembre",
      ownerName: "Pau",
      status: "planned",
      progressPercent: null,
    },
    {
      slug: "person-pms-daily-account-relations",
      level: "person",
      areaKey: "account-pm",
      title: "Sostener la relación diaria de cada cuenta",
      metric: "Relación, próximo paso y riesgo por cuenta",
      target: "Cada cuenta activa con seguimiento directo y próximo paso fechado",
      ownerName: "PMs",
      status: "planned",
      progressPercent: null,
    },
    {
      slug: "person-pms-expansion-detection",
      level: "person",
      areaKey: "account-pm",
      title: "Conseguir reuniones y detectar oportunidades",
      metric: "Reuniones y oportunidades detectadas por PMs",
      target: "Aportar al menos una oportunidad de ampliación originada por el equipo",
      ownerName: "PMs",
      status: "planned",
      progressPercent: null,
    },
    {
      slug: "person-pms-kimberly-value",
      level: "person",
      areaKey: "account-pm",
      title: "Liderar la sesión de valor de Kimberly",
      metric: "Sesión realizada con Insights y minuta",
      target: "Sesión de valor junto a Vicky al 12 de septiembre",
      ownerName: "PMs",
      status: "planned",
      progressPercent: null,
    },
    {
      slug: "person-pms-cases-references",
      level: "person",
      areaKey: "account-pm",
      title: "Aportar insumos para casos y referencias",
      metric: "Insumos de cliente aprobados",
      target: "Aportar evidencia para casos escritos, testimonios y referencias sin negociar precio",
      ownerName: "PMs",
      status: "planned",
      progressPercent: null,
    },
    {
      slug: "person-pms-no-price-negotiation",
      level: "person",
      areaKey: "account-pm",
      title: "Sostener la relación sin negociar precio",
      metric: "Interacciones con escalamiento correcto",
      target: "PMs consiguen reuniones y escalan precio/cierre a Vicky o Tomás",
      ownerName: "PMs",
      status: "planned",
      progressPercent: null,
    },
  ],

  accounts: [
    { slug: "warner-marketing", name: "Warner Marketing" },
    { slug: "warner-insights", name: "Warner Insights" },
    { slug: "warner-otras-areas", name: "Warner otras áreas" },
    { slug: "kimberly-clark", name: "Kimberly-Clark" },
    { slug: "uber", name: "Uber" },
    { slug: "uber-eats", name: "Uber Eats" },
    { slug: "pedidosya", name: "PedidosYa" },
    { slug: "bid", name: "BID" },
    { slug: "coelsa", name: "COELSA" },
    { slug: "bcra", name: "BCRA" },
    { slug: "pepsico", name: "PepsiCo" },
    { slug: "cafe-martinez", name: "Café Martínez" },
    { slug: "roche", name: "Roche" },
    { slug: "mercedes-benz", name: "Mercedes-Benz" },
    { slug: "unilever", name: "Unilever" },
    { slug: "red-bull", name: "Red Bull" },
    { slug: "ccu", name: "CCU" },
    { slug: "nestle", name: "Nestlé" },
    { slug: "mondelez", name: "Mondelez" },
    { slug: "mercado-libre", name: "Mercado Libre" },
    { slug: "animal-studio", name: "Animal Studio" },
    { slug: "google", name: "Google" },
    { slug: "belcorp", name: "Belcorp" },
    { slug: "osde", name: "Osde" },
    { slug: "oxean", name: "Oxean" },
  ],

  actions: [
    // Septiembre — 1–7 sep.
    {
      slug: "sep-w1-tomas-objectives-vicky",
      objectiveSlug: "company-month-sep-open-mesas",
      accountSlug: null,
      title: "Reunión de objetivos con Vicky",
      description: "Retrospectiva y bajada del plan septiembre–diciembre.",
      month: "septiembre",
      weekLabel: "1–7 sep",
      weekStart: "2026-09-01",
      dueDate: null,
      focus: "dirección",
      accountableOwnerName: "Tomás",
      supportingOwnerNames: ["Vicky"],
      status: "planned",
      dependencySlugs: [],
      sortOrder: 1,
    },
    {
      slug: "sep-w1-tomas-bcra-range",
      objectiveSlug: "company-bcra-decision",
      accountSlug: "bcra",
      title: "Aclarar con BCRA el rango histórico",
      description: "Confirmar marzo versus julio porque define el costo de carga del histórico.",
      month: "septiembre",
      weekLabel: "1–7 sep",
      weekStart: "2026-09-01",
      dueDate: null,
      focus: "cierre piloto",
      accountableOwnerName: "Tomás",
      supportingOwnerNames: [],
      status: "planned",
      dependencySlugs: [],
      sortOrder: 2,
    },
    {
      slug: "sep-w1-vicky-warner-insights-annex",
      objectiveSlug: "area-operations-warner-sequence",
      accountSlug: "warner-insights",
      title: "Presentar el anexo Warner Insights",
      description: "Presentar los escalones de créditos adicionales.",
      month: "septiembre",
      weekLabel: "1–7 sep",
      weekStart: "2026-09-01",
      dueDate: null,
      focus: "expansión",
      accountableOwnerName: "Vicky",
      supportingOwnerNames: [],
      status: "planned",
      dependencySlugs: [],
      sortOrder: 3,
    },
    {
      slug: "sep-w1-pm-kimberly-value-request",
      objectiveSlug: "person-pms-kimberly-value",
      accountSlug: "kimberly-clark",
      title: "Pedir la sesión de valor de Kimberly",
      description: "La PM de Kimberly pide la sesión e invita al referente de Insights del cliente.",
      month: "septiembre",
      weekLabel: "1–7 sep",
      weekStart: "2026-09-01",
      dueDate: null,
      focus: "retención y expansión",
      accountableOwnerName: "PMs",
      supportingOwnerNames: ["Vicky"],
      status: "planned",
      dependencySlugs: [],
      sortOrder: 4,
    },
    {
      slug: "sep-w1-tomas-ask-pau-warner-mexico",
      objectiveSlug: "person-pau-warner-mexico-access",
      accountSlug: "warner-marketing",
      title: "Pedir a Pau la reunión Warner México",
      description: "Conseguir la reunión de Anticipación Estratégica antes del 30/09.",
      month: "septiembre",
      weekLabel: "1–7 sep",
      weekStart: "2026-09-01",
      dueDate: "2026-09-30",
      focus: "apertura estratégica",
      accountableOwnerName: "Tomás",
      supportingOwnerNames: ["Pau"],
      status: "planned",
      dependencySlugs: [],
      sortOrder: 5,
    },
    {
      slug: "sep-w1-vicky-bid-proposal",
      objectiveSlug: "company-new-business-proposals",
      accountSlug: "bid",
      title: "Cerrar y enviar la propuesta BID",
      description: "Completar la licitación NI-T1340; vence el 7/9.",
      month: "septiembre",
      weekLabel: "1–7 sep",
      weekStart: "2026-09-01",
      dueDate: "2026-09-07",
      focus: "nuevo negocio",
      accountableOwnerName: "Vicky",
      supportingOwnerNames: ["Tomás"],
      status: "planned",
      dependencySlugs: [],
      sortOrder: 6,
    },
    {
      slug: "sep-w1-vicky-cascade-acha-goals",
      objectiveSlug: "person-vicky-coordination",
      accountSlug: null,
      title: "Bajar objetivos a Acha",
      description: "Vicky baja a Acha los objetivos que recibió para el cuatrimestre.",
      month: "septiembre",
      weekLabel: "1–7 sep",
      weekStart: "2026-09-01",
      dueDate: null,
      focus: "operación",
      accountableOwnerName: "Vicky",
      supportingOwnerNames: ["Acha"],
      status: "planned",
      dependencySlugs: ["sep-w1-tomas-objectives-vicky"],
      sortOrder: 7,
    },

    // Septiembre — 8–14 sep.
    {
      slug: "sep-w2-vicky-kimberly-value-session",
      objectiveSlug: "area-operations-kimberly-expansion",
      accountSlug: "kimberly-clark",
      title: "Realizar la sesión de valor con Kimberly-Clark",
      description: "Sesión PM + Vicky con Insights del cliente; Tomás sólo escala si aparece riesgo.",
      month: "septiembre",
      weekLabel: "8–14 sep",
      weekStart: "2026-09-08",
      dueDate: "2026-09-12",
      focus: "retención y expansión",
      accountableOwnerName: "Vicky",
      supportingOwnerNames: ["PMs"],
      status: "planned",
      dependencySlugs: ["sep-w1-pm-kimberly-value-request"],
      sortOrder: 8,
    },
    {
      slug: "sep-w2-tomas-pepsico-follow-up",
      objectiveSlug: "person-tomas-strategic-opportunities",
      accountSlug: "pepsico",
      title: "Dar seguimiento a PepsiCo",
      description: "Seguir la propuesta enviada el 24/8 hasta obtener respuesta o reunión de decisión.",
      month: "septiembre",
      weekLabel: "8–14 sep",
      weekStart: "2026-09-08",
      dueDate: null,
      focus: "nuevo negocio",
      accountableOwnerName: "Tomás",
      supportingOwnerNames: [],
      status: "planned",
      dependencySlugs: [],
      sortOrder: 9,
    },
    {
      slug: "sep-w2-tomas-vicky-triggers-meeting",
      objectiveSlug: "company-triggers-product",
      accountSlug: null,
      title: "Realizar la reunión de triggers",
      description: "Tomás presenta el producto y Vicky arma el plan operativo.",
      month: "septiembre",
      weekLabel: "8–14 sep",
      weekStart: "2026-09-08",
      dueDate: null,
      focus: "producto y precio",
      accountableOwnerName: "Tomás",
      supportingOwnerNames: ["Vicky"],
      status: "planned",
      dependencySlugs: [],
      sortOrder: 10,
    },
    {
      slug: "sep-w2-tomas-uber-fee-follow-up",
      objectiveSlug: "company-uber-reputational",
      accountSlug: "uber",
      title: "Dar seguimiento a la propuesta de fee de Uber",
      description: "Seguir la propuesta mensual ya presentada.",
      month: "septiembre",
      weekLabel: "8–14 sep",
      weekStart: "2026-09-08",
      dueDate: null,
      focus: "expansión",
      accountableOwnerName: "Tomás",
      supportingOwnerNames: [],
      status: "planned",
      dependencySlugs: [],
      sortOrder: 11,
    },
    {
      slug: "sep-w2-tomas-uber-chile-intro",
      objectiveSlug: "company-uber-reputational",
      accountSlug: "uber",
      title: "Pedir presentación con Asuntos Públicos Chile",
      description: "Abrir la puerta Reputacional vía presentación con Asuntos Públicos Chile.",
      month: "septiembre",
      weekLabel: "8–14 sep",
      weekStart: "2026-09-08",
      dueDate: null,
      focus: "apertura estratégica",
      accountableOwnerName: "Tomás",
      supportingOwnerNames: [],
      status: "planned",
      dependencySlugs: ["sep-w2-tomas-uber-fee-follow-up"],
      sortOrder: 12,
    },
    {
      slug: "sep-w2-tomas-redbull-follow-up",
      objectiveSlug: "person-tomas-strategic-opportunities",
      accountSlug: "red-bull",
      title: "Dar seguimiento a Red Bull",
      description: "Seguir a Eugenia Rojas después del envío de credenciales.",
      month: "septiembre",
      weekLabel: "8–14 sep",
      weekStart: "2026-09-08",
      dueDate: null,
      focus: "seguimiento largo",
      accountableOwnerName: "Tomás",
      supportingOwnerNames: [],
      status: "planned",
      dependencySlugs: [],
      sortOrder: 13,
    },
    {
      slug: "sep-w2-vicky-warner-piracy-draft",
      objectiveSlug: "area-operations-warner-sequence",
      accountSlug: "warner-insights",
      title: "Armar la propuesta Piracy Warner",
      description: "Preparar la propuesta después de la llamada con Mónica.",
      month: "septiembre",
      weekLabel: "8–14 sep",
      weekStart: "2026-09-08",
      dueDate: null,
      focus: "expansión",
      accountableOwnerName: "Vicky",
      supportingOwnerNames: [],
      status: "planned",
      dependencySlugs: ["sep-w1-vicky-warner-insights-annex"],
      sortOrder: 14,
    },
    {
      slug: "sep-w2-tomas-commercial-monday",
      objectiveSlug: "company-month-sep-open-mesas",
      accountSlug: null,
      title: "Instalar la reunión comercial de los lunes",
      description: "Primera reunión comercial; queda instalada semanalmente.",
      month: "septiembre",
      weekLabel: "8–14 sep",
      weekStart: "2026-09-08",
      dueDate: null,
      focus: "ritual de ejecución",
      accountableOwnerName: "Tomás",
      supportingOwnerNames: ["Vicky", "Sil", "Santi"],
      status: "planned",
      dependencySlugs: ["sep-w1-tomas-objectives-vicky"],
      sortOrder: 15,
    },

    // Septiembre — 15–21 sep.
    {
      slug: "sep-w3-vicky-kimberly-proposal",
      objectiveSlug: "company-kimberly-renewal-price",
      accountSlug: "kimberly-clark",
      title: "Enviar propuesta Kimberly",
      description: "Enviar la propuesta con precio de ventana y vencimiento.",
      month: "septiembre",
      weekLabel: "15–21 sep",
      weekStart: "2026-09-15",
      dueDate: null,
      focus: "retención y expansión",
      accountableOwnerName: "Vicky",
      supportingOwnerNames: [],
      status: "planned",
      dependencySlugs: ["sep-w2-vicky-kimberly-value-session"],
      sortOrder: 16,
    },
    {
      slug: "sep-w3-vicky-pedidosya-proposal",
      objectiveSlug: "area-operations-pedidosya-recurring",
      accountSlug: "pedidosya",
      title: "Enviar propuesta PedidosYa",
      description: "Enviar la propuesta para convertir el proyecto en recurrencia.",
      month: "septiembre",
      weekLabel: "15–21 sep",
      weekStart: "2026-09-15",
      dueDate: null,
      focus: "expansión",
      accountableOwnerName: "Vicky",
      supportingOwnerNames: [],
      status: "planned",
      dependencySlugs: [],
      sortOrder: 17,
    },
    {
      slug: "sep-w3-acha-license-audit-start",
      objectiveSlug: "person-acha-license-audit",
      accountSlug: null,
      title: "Arrancar la auditoría de licencias",
      description: "Comparar uso real versus costo de herramientas y licencias.",
      month: "septiembre",
      weekLabel: "15–21 sep",
      weekStart: "2026-09-15",
      dueDate: null,
      focus: "operación",
      accountableOwnerName: "Acha",
      supportingOwnerNames: [],
      status: "planned",
      dependencySlugs: ["sep-w1-vicky-cascade-acha-goals"],
      sortOrder: 18,
    },
    {
      slug: "sep-w3-santi-first-content",
      objectiveSlug: "area-marketing-linkedin",
      accountSlug: null,
      title: "Publicar la primera pieza de contenido del mes",
      description: "Pieza basada en un hallazgo del Radar.",
      month: "septiembre",
      weekLabel: "15–21 sep",
      weekStart: "2026-09-15",
      dueDate: null,
      focus: "demanda",
      accountableOwnerName: "Santi",
      supportingOwnerNames: [],
      status: "planned",
      dependencySlugs: [],
      sortOrder: 19,
    },

    // Septiembre — 22–30 sep.
    {
      slug: "sep-w4-tomas-bcra-pilot",
      objectiveSlug: "company-bcra-decision",
      accountSlug: "bcra",
      title: "Entregar la prueba piloto BCRA",
      description: "Entregar base de menciones verificada y reporte de precisión.",
      month: "septiembre",
      weekLabel: "22–30 sep",
      weekStart: "2026-09-22",
      dueDate: null,
      focus: "cierre piloto",
      accountableOwnerName: "Tomás",
      supportingOwnerNames: ["Acha"],
      status: "planned",
      dependencySlugs: ["sep-w1-tomas-bcra-range"],
      sortOrder: 20,
    },
    {
      slug: "sep-w4-tomas-warner-mexico-meeting",
      objectiveSlug: "company-warner-mexico",
      accountSlug: "warner-marketing",
      title: "Realizar o escalar la reunión Warner México",
      description: "Si se agendó, realizar la reunión; si no, escalar con Pau.",
      month: "septiembre",
      weekLabel: "22–30 sep",
      weekStart: "2026-09-22",
      dueDate: "2026-09-30",
      focus: "apertura estratégica",
      accountableOwnerName: "Tomás",
      supportingOwnerNames: ["Pau"],
      status: "planned",
      dependencySlugs: ["sep-w1-tomas-ask-pau-warner-mexico"],
      sortOrder: 21,
    },
    {
      slug: "sep-w4-vicky-follow-proposals",
      objectiveSlug: "company-month-sep-open-mesas",
      accountSlug: null,
      title: "Dar seguimiento a las propuestas enviadas",
      description: "Seguir Kimberly y PedidosYa.",
      month: "septiembre",
      weekLabel: "22–30 sep",
      weekStart: "2026-09-22",
      dueDate: null,
      focus: "cierre",
      accountableOwnerName: "Vicky",
      supportingOwnerNames: [],
      status: "planned",
      dependencySlugs: ["sep-w3-vicky-kimberly-proposal", "sep-w3-vicky-pedidosya-proposal"],
      sortOrder: 22,
    },
    {
      slug: "sep-w4-acha-license-audit-decision",
      objectiveSlug: "area-operations-licenses",
      accountSlug: null,
      title: "Cerrar la auditoría de licencias con decisión",
      description: "Documentar baja o consolidación de herramientas.",
      month: "septiembre",
      weekLabel: "22–30 sep",
      weekStart: "2026-09-22",
      dueDate: null,
      focus: "operación",
      accountableOwnerName: "Acha",
      supportingOwnerNames: [],
      status: "planned",
      dependencySlugs: ["sep-w3-acha-license-audit-start"],
      sortOrder: 23,
    },
    {
      slug: "sep-w4-tomas-triggers-approval",
      objectiveSlug: "company-triggers-product",
      accountSlug: null,
      title: "Aprobar el documento de triggers",
      description: "Cerrar producto, precio y plan operativo.",
      month: "septiembre",
      weekLabel: "22–30 sep",
      weekStart: "2026-09-22",
      dueDate: "2026-09-30",
      focus: "producto y precio",
      accountableOwnerName: "Tomás",
      supportingOwnerNames: ["Vicky"],
      status: "planned",
      dependencySlugs: ["sep-w2-tomas-vicky-triggers-meeting"],
      sortOrder: 24,
    },

    // Octubre — 1–5 oct.
    {
      slug: "oct-w1-tomas-october-checkpoint",
      objectiveSlug: "company-month-oct-advance",
      accountSlug: null,
      title: "Realizar el punto de control del 6 de octubre",
      description: "Lo que no está en negociación activa no firma en 2026: decidir qué se persigue y qué pasa a oportunidades 2027.",
      month: "octubre",
      weekLabel: "1–5 oct",
      weekStart: "2026-10-01",
      dueDate: "2026-10-06",
      focus: "control comercial",
      accountableOwnerName: "Tomás",
      supportingOwnerNames: ["Vicky"],
      status: "planned",
      dependencySlugs: ["sep-w4-vicky-follow-proposals"],
      sortOrder: 25,
    },
    {
      slug: "oct-w1-vicky-kimberly-hard-follow-up",
      objectiveSlug: "company-kimberly-renewal-price",
      accountSlug: "kimberly-clark",
      title: "Hacer seguimiento duro de Kimberly",
      description: "Llamada, no mail.",
      month: "octubre",
      weekLabel: "1–5 oct",
      weekStart: "2026-10-01",
      dueDate: null,
      focus: "retención y expansión",
      accountableOwnerName: "Vicky",
      supportingOwnerNames: [],
      status: "planned",
      dependencySlugs: ["sep-w3-vicky-kimberly-proposal"],
      sortOrder: 26,
    },
    {
      slug: "oct-w1-vicky-ask-referrals",
      objectiveSlug: "area-product-agency-channel",
      accountSlug: null,
      title: "Pedir referidos a dos cuentas satisfechas",
      description: "Solicitar intros a dos cuentas satisfechas.",
      month: "octubre",
      weekLabel: "1–5 oct",
      weekStart: "2026-10-01",
      dueDate: null,
      focus: "referidos",
      accountableOwnerName: "Vicky",
      supportingOwnerNames: [],
      status: "planned",
      dependencySlugs: [],
      sortOrder: 27,
    },
    {
      slug: "oct-w1-tomas-cordoba-talk",
      objectiveSlug: "company-month-oct-advance",
      accountSlug: null,
      title: "Armar la charla de Córdoba",
      description: "Preparar la charla sobre material existente para el 30/10.",
      month: "octubre",
      weekLabel: "1–5 oct",
      weekStart: "2026-10-01",
      dueDate: "2026-10-30",
      focus: "Conversaciones de Frontera",
      accountableOwnerName: "Tomás",
      supportingOwnerNames: [],
      status: "planned",
      dependencySlugs: [],
      sortOrder: 28,
    },

    // Octubre — 6–12 oct.
    {
      slug: "oct-w2-vicky-kimberly-negotiation",
      objectiveSlug: "company-kimberly-renewal-price",
      accountSlug: "kimberly-clark",
      title: "Negociar Kimberly",
      description: "Reunión de objeciones y ajuste.",
      month: "octubre",
      weekLabel: "6–12 oct",
      weekStart: "2026-10-06",
      dueDate: null,
      focus: "retención y expansión",
      accountableOwnerName: "Vicky",
      supportingOwnerNames: ["Tomás"],
      status: "planned",
      dependencySlugs: ["oct-w1-vicky-kimberly-hard-follow-up"],
      sortOrder: 29,
    },
    {
      slug: "oct-w2-vicky-pedidosya-close",
      objectiveSlug: "area-operations-pedidosya-recurring",
      accountSlug: "pedidosya",
      title: "Empujar el cierre de PedidosYa",
      description: "Llevar el acuerdo verbal o firma de la recurrencia.",
      month: "octubre",
      weekLabel: "6–12 oct",
      weekStart: "2026-10-06",
      dueDate: null,
      focus: "cierre",
      accountableOwnerName: "Vicky",
      supportingOwnerNames: [],
      status: "planned",
      dependencySlugs: ["sep-w3-vicky-pedidosya-proposal"],
      sortOrder: 30,
    },
    {
      slug: "oct-w2-tomas-bcra-decision",
      objectiveSlug: "company-bcra-decision",
      accountSlug: "bcra",
      title: "Pedir reunión de decisión BCRA",
      description: "Dar seguimiento post-prueba piloto con la propuesta de servicio gestionado sobre la mesa.",
      month: "octubre",
      weekLabel: "6–12 oct",
      weekStart: "2026-10-06",
      dueDate: null,
      focus: "cierre piloto",
      accountableOwnerName: "Tomás",
      supportingOwnerNames: [],
      status: "planned",
      dependencySlugs: ["sep-w4-tomas-bcra-pilot"],
      sortOrder: 31,
    },
    {
      slug: "oct-w2-tomas-pepsico-decision",
      objectiveSlug: "person-tomas-strategic-opportunities",
      accountSlug: "pepsico",
      title: "Dar seguimiento a PepsiCo hasta decisión",
      description: "Buscar respuesta formal o reunión de decisión.",
      month: "octubre",
      weekLabel: "6–12 oct",
      weekStart: "2026-10-06",
      dueDate: null,
      focus: "nuevo negocio",
      accountableOwnerName: "Tomás",
      supportingOwnerNames: [],
      status: "planned",
      dependencySlugs: ["sep-w2-tomas-pepsico-follow-up"],
      sortOrder: 32,
    },
    {
      slug: "oct-w2-tomas-google-follow-up",
      objectiveSlug: "person-tomas-strategic-opportunities",
      accountSlug: "google",
      title: "Reactivar Google si no responde",
      description: "Dar seguimiento a Caro si no hubo respuesta.",
      month: "octubre",
      weekLabel: "6–12 oct",
      weekStart: "2026-10-06",
      dueDate: null,
      focus: "seguimiento largo",
      accountableOwnerName: "Tomás",
      supportingOwnerNames: [],
      status: "planned",
      dependencySlugs: [],
      sortOrder: 33,
    },

    // Octubre — 13–19 oct.
    {
      slug: "oct-w3-vicky-kimberly-expansion-window",
      objectiveSlug: "area-operations-kimberly-expansion",
      accountSlug: "kimberly-clark",
      title: "Integrar la expansión Kimberly en la renovación",
      description: "Usar la última ventana cómoda, manteniendo la expansión como anexo separado.",
      month: "octubre",
      weekLabel: "13–19 oct",
      weekStart: "2026-10-13",
      dueDate: null,
      focus: "retención y expansión",
      accountableOwnerName: "Vicky",
      supportingOwnerNames: [],
      status: "planned",
      dependencySlugs: ["oct-w2-vicky-kimberly-negotiation"],
      sortOrder: 34,
    },
    {
      slug: "oct-w3-tomas-warner-proposal",
      objectiveSlug: "company-warner-mexico",
      accountSlug: "warner-marketing",
      title: "Enviar la propuesta Warner",
      description: "Enviar Anticipación Estratégica si la reunión fue en septiembre/octubre.",
      month: "octubre",
      weekLabel: "13–19 oct",
      weekStart: "2026-10-13",
      dueDate: "2026-10-24",
      focus: "apertura estratégica",
      accountableOwnerName: "Tomás",
      supportingOwnerNames: ["Pau"],
      status: "planned",
      dependencySlugs: ["sep-w4-tomas-warner-mexico-meeting"],
      sortOrder: 35,
    },
    {
      slug: "oct-w3-tomas-uber-meeting",
      objectiveSlug: "company-uber-reputational",
      accountSlug: "uber",
      title: "Realizar la reunión Uber",
      description: "Realizarla si llegó la presentación; si no, hacer un segundo pedido.",
      month: "octubre",
      weekLabel: "13–19 oct",
      weekStart: "2026-10-13",
      dueDate: null,
      focus: "apertura estratégica",
      accountableOwnerName: "Tomás",
      supportingOwnerNames: [],
      status: "planned",
      dependencySlugs: ["sep-w2-tomas-uber-chile-intro"],
      sortOrder: 36,
    },

    // Octubre — 20–26 oct.
    {
      slug: "oct-w4-tomas-close-pending",
      objectiveSlug: "company-month-oct-advance",
      accountSlug: null,
      title: "Cerrar pendientes antes del viaje a Córdoba",
      description: "Dejar resueltos los pendientes comerciales y de preparación.",
      month: "octubre",
      weekLabel: "20–26 oct",
      weekStart: "2026-10-20",
      dueDate: null,
      focus: "ejecución",
      accountableOwnerName: "Tomás",
      supportingOwnerNames: [],
      status: "planned",
      dependencySlugs: ["oct-w3-tomas-warner-proposal", "oct-w3-tomas-uber-meeting"],
      sortOrder: 37,
    },
    {
      slug: "oct-w4-tomas-rehearse-cordoba",
      objectiveSlug: "company-month-oct-advance",
      accountSlug: null,
      title: "Ensayar y ajustar la charla",
      description: "Ensayar y ajustar la charla de Córdoba.",
      month: "octubre",
      weekLabel: "20–26 oct",
      weekStart: "2026-10-20",
      dueDate: "2026-10-30",
      focus: "Conversaciones de Frontera",
      accountableOwnerName: "Tomás",
      supportingOwnerNames: [],
      status: "planned",
      dependencySlugs: ["oct-w1-tomas-cordoba-talk"],
      sortOrder: 38,
    },
    {
      slug: "oct-w4-vicky-operations-readiness",
      objectiveSlug: "area-operations-on-time-delivery",
      accountSlug: null,
      title: "Revisar la capacidad operativa",
      description: "Confirmar que el equipo está listo si algo se firma en noviembre.",
      month: "octubre",
      weekLabel: "20–26 oct",
      weekStart: "2026-10-20",
      dueDate: null,
      focus: "operación",
      accountableOwnerName: "Vicky",
      supportingOwnerNames: ["PMs", "Acha"],
      status: "planned",
      dependencySlugs: [],
      sortOrder: 39,
    },

    // Octubre — 27–31 oct.
    {
      slug: "oct-w5-tomas-frontier-event",
      objectiveSlug: "company-month-oct-advance",
      accountSlug: null,
      title: "Presentar Conversaciones de Frontera",
      description: "El 30/10: dar la charla y cargar al menos cinco contactos calificados y dos reuniones para la semana siguiente.",
      month: "octubre",
      weekLabel: "27–31 oct",
      weekStart: "2026-10-27",
      dueDate: "2026-10-30",
      focus: "generación de demanda",
      accountableOwnerName: "Tomás",
      supportingOwnerNames: [],
      status: "planned",
      dependencySlugs: ["oct-w4-tomas-rehearse-cordoba"],
      sortOrder: 40,
    },
    {
      slug: "oct-w5-santi-frontier-content",
      objectiveSlug: "area-marketing-frontier-content",
      accountSlug: null,
      title: "Publicar contenido derivado del evento",
      description: "Publicar la pieza derivada de Frontera en la semana siguiente, antes del 6/11.",
      month: "octubre",
      weekLabel: "27–31 oct",
      weekStart: "2026-10-27",
      dueDate: "2026-11-06",
      focus: "demanda",
      accountableOwnerName: "Santi",
      supportingOwnerNames: [],
      status: "planned",
      dependencySlugs: ["oct-w5-tomas-frontier-event"],
      sortOrder: 41,
    },

    // Noviembre — 3–9 nov.
    {
      slug: "nov-w1-tomas-close-checkpoint",
      objectiveSlug: "company-month-nov-close",
      accountSlug: null,
      title: "Realizar el punto de control de cierre del 3 de noviembre",
      description: "Revisar el estado real de cada negociación y decidir el foco.",
      month: "noviembre",
      weekLabel: "3–9 nov",
      weekStart: "2026-11-03",
      dueDate: "2026-11-03",
      focus: "control comercial",
      accountableOwnerName: "Tomás",
      supportingOwnerNames: ["Vicky"],
      status: "planned",
      dependencySlugs: ["oct-w1-tomas-october-checkpoint"],
      sortOrder: 42,
    },
    {
      slug: "nov-w1-tomas-frontier-meetings",
      objectiveSlug: "company-month-nov-close",
      accountSlug: null,
      title: "Reunirse con los contactos de Frontera",
      description: "Tomar las reuniones con los contactos calificados antes de que se enfríen.",
      month: "noviembre",
      weekLabel: "3–9 nov",
      weekStart: "2026-11-03",
      dueDate: null,
      focus: "nuevo negocio",
      accountableOwnerName: "Tomás",
      supportingOwnerNames: [],
      status: "planned",
      dependencySlugs: ["oct-w5-tomas-frontier-event"],
      sortOrder: 43,
    },
    {
      slug: "nov-w1-tomas-vicky-commercial-only",
      objectiveSlug: "company-new-recurring-signed",
      accountSlug: null,
      title: "Pasar a agenda comercial exclusiva si no hay firma cerca",
      description: "Tomás y Vicky dedican las próximas dos semanas a agenda comercial si no hay una firma cercana.",
      month: "noviembre",
      weekLabel: "3–9 nov",
      weekStart: "2026-11-03",
      dueDate: null,
      focus: "cierre",
      accountableOwnerName: "Tomás",
      supportingOwnerNames: ["Vicky"],
      status: "planned",
      dependencySlugs: ["nov-w1-tomas-close-checkpoint"],
      sortOrder: 44,
    },

    // Noviembre — 10–16 nov.
    {
      slug: "nov-w2-vicky-final-negotiation",
      objectiveSlug: "company-expansion-fee",
      accountSlug: null,
      title: "Liderar la negociación final de la cuenta más avanzada",
      description: "Empujar el cierre de la oportunidad con mayor probabilidad.",
      month: "noviembre",
      weekLabel: "10–16 nov",
      weekStart: "2026-11-10",
      dueDate: null,
      focus: "cierre",
      accountableOwnerName: "Vicky",
      supportingOwnerNames: ["Tomás"],
      status: "planned",
      dependencySlugs: ["nov-w1-tomas-close-checkpoint"],
      sortOrder: 45,
    },
    {
      slug: "nov-w2-tomas-bid-decision",
      objectiveSlug: "company-new-business-proposals",
      accountSlug: "bid",
      title: "Tomar decisión BID",
      description: "Definir fecha dura o pasar formalmente a oportunidades 2027.",
      month: "noviembre",
      weekLabel: "10–16 nov",
      weekStart: "2026-11-10",
      dueDate: null,
      focus: "decisión",
      accountableOwnerName: "Tomás",
      supportingOwnerNames: [],
      status: "planned",
      dependencySlugs: ["sep-w1-vicky-bid-proposal"],
      sortOrder: 46,
    },
    {
      slug: "nov-w2-vicky-capacity-review",
      objectiveSlug: "area-operations-on-time-delivery",
      accountSlug: null,
      title: "Revisar capacidad para el arranque",
      description: "Confirmar capacidad operativa para aquello que se firme.",
      month: "noviembre",
      weekLabel: "10–16 nov",
      weekStart: "2026-11-10",
      dueDate: null,
      focus: "operación",
      accountableOwnerName: "Vicky",
      supportingOwnerNames: ["PMs", "Acha"],
      status: "planned",
      dependencySlugs: ["oct-w4-vicky-operations-readiness"],
      sortOrder: 47,
    },

    // Noviembre — 17–23 nov.
    {
      slug: "nov-w3-vicky-first-expansion-signature",
      objectiveSlug: "company-expansion-fee",
      accountSlug: null,
      title: "Buscar la firma de la primera expansión",
      description: "Objetivo de firma efectiva de PedidosYa, BID o Kimberly ampliada.",
      month: "noviembre",
      weekLabel: "17–23 nov",
      weekStart: "2026-11-17",
      dueDate: null,
      focus: "cierre",
      accountableOwnerName: "Vicky",
      supportingOwnerNames: ["Tomás"],
      status: "planned",
      dependencySlugs: ["nov-w2-vicky-final-negotiation"],
      sortOrder: 48,
    },
    {
      slug: "nov-w3-tomas-2027-draft-start",
      objectiveSlug: "company-2027-opportunities",
      accountSlug: null,
      title: "Iniciar el borrador de oportunidades 2027",
      description: "Listar qué queda vivo y con qué monto estimado.",
      month: "noviembre",
      weekLabel: "17–23 nov",
      weekStart: "2026-11-17",
      dueDate: null,
      focus: "planificación 2027",
      accountableOwnerName: "Tomás",
      supportingOwnerNames: [],
      status: "planned",
      dependencySlugs: ["nov-w2-tomas-bid-decision"],
      sortOrder: 49,
    },

    // Noviembre — 24–30 nov.
    {
      slug: "nov-w4-vicky-kimberly-resolution",
      objectiveSlug: "company-kimberly-renewal-price",
      accountSlug: "kimberly-clark",
      title: "Resolver definitivamente la renovación Kimberly",
      description: "Cerrar la renovación esta semana.",
      month: "noviembre",
      weekLabel: "24–30 nov",
      weekStart: "2026-11-24",
      dueDate: null,
      focus: "retención",
      accountableOwnerName: "Vicky",
      supportingOwnerNames: [],
      status: "planned",
      dependencySlugs: ["oct-w3-vicky-kimberly-expansion-window"],
      sortOrder: 50,
    },
    {
      slug: "nov-w4-vicky-start-signed-work",
      objectiveSlug: "company-on-time-delivery",
      accountSlug: null,
      title: "Arrancar lo firmado sin afectar las demás cuentas",
      description: "Si hubo firma, comenzar el trabajo sin comprometer la operación recurrente.",
      month: "noviembre",
      weekLabel: "24–30 nov",
      weekStart: "2026-11-24",
      dueDate: null,
      focus: "operación",
      accountableOwnerName: "Vicky",
      supportingOwnerNames: ["PMs", "Acha"],
      status: "planned",
      dependencySlugs: ["nov-w3-vicky-first-expansion-signature"],
      sortOrder: 51,
    },
    {
      slug: "nov-w4-tomas-2027-draft-complete",
      objectiveSlug: "company-2027-opportunities",
      accountSlug: null,
      title: "Completar el borrador de oportunidades 2027",
      description: "Dejar completo el primer borrador con oportunidades vivas y montos estimados.",
      month: "noviembre",
      weekLabel: "24–30 nov",
      weekStart: "2026-11-24",
      dueDate: "2026-11-30",
      focus: "planificación 2027",
      accountableOwnerName: "Tomás",
      supportingOwnerNames: [],
      status: "planned",
      dependencySlugs: ["nov-w3-tomas-2027-draft-start"],
      sortOrder: 52,
    },

    // Diciembre — 1–7 dic.
    {
      slug: "dec-w1-vicky-kimberly-final-pressure",
      objectiveSlug: "company-kimberly-renewal-price",
      accountSlug: "kimberly-clark",
      title: "Ejercer presión final sobre Kimberly",
      description: "Seguir la firma de la renovación con precio corregido.",
      month: "diciembre",
      weekLabel: "1–7 dic",
      weekStart: "2026-12-01",
      dueDate: null,
      focus: "retención",
      accountableOwnerName: "Vicky",
      supportingOwnerNames: [],
      status: "planned",
      dependencySlugs: ["nov-w4-vicky-kimberly-resolution"],
      sortOrder: 53,
    },
    {
      slug: "dec-w1-tomas-year-review",
      objectiveSlug: "company-month-dec-renew",
      accountSlug: null,
      title: "Revisar el año",
      description: "Revisar qué se firmó, qué quedó abierto y qué se aprendió.",
      month: "diciembre",
      weekLabel: "1–7 dic",
      weekStart: "2026-12-01",
      dueDate: null,
      focus: "revisión anual",
      accountableOwnerName: "Tomás",
      supportingOwnerNames: ["Vicky"],
      status: "planned",
      dependencySlugs: ["nov-w4-tomas-2027-draft-complete"],
      sortOrder: 54,
    },

    // Diciembre — 8–14 dic.
    {
      slug: "dec-w2-vicky-administrative-closing",
      objectiveSlug: "company-new-monthly-fee",
      accountSlug: null,
      title: "Cerrar administrativamente lo firmado",
      description: "Completar contratos y facturación de todo lo firmado.",
      month: "diciembre",
      weekLabel: "8–14 dic",
      weekStart: "2026-12-08",
      dueDate: null,
      focus: "facturación",
      accountableOwnerName: "Vicky",
      supportingOwnerNames: [],
      status: "planned",
      dependencySlugs: ["nov-w3-vicky-first-expansion-signature"],
      sortOrder: 55,
    },
    {
      slug: "dec-w2-vicky-final-feedback-ones",
      objectiveSlug: "person-vicky-team-feedback",
      accountSlug: null,
      title: "Completar los últimos 1:1 de devolución",
      description: "Cerrar los 1:1 pendientes con el equipo.",
      month: "diciembre",
      weekLabel: "8–14 dic",
      weekStart: "2026-12-08",
      dueDate: "2026-12-15",
      focus: "equipo",
      accountableOwnerName: "Vicky",
      supportingOwnerNames: [],
      status: "planned",
      dependencySlugs: [],
      sortOrder: 56,
    },

    // Diciembre — 15–21 dic.
    {
      slug: "dec-w3-vicky-kimberly-deadline",
      objectiveSlug: "company-kimberly-renewal-price",
      accountSlug: "kimberly-clark",
      title: "Cumplir la fecha límite dura de Kimberly",
      description: "Renovación firmada con precio corregido el 21/12.",
      month: "diciembre",
      weekLabel: "15–21 dic",
      weekStart: "2026-12-15",
      dueDate: "2026-12-21",
      focus: "retención",
      accountableOwnerName: "Vicky",
      supportingOwnerNames: [],
      status: "planned",
      dependencySlugs: ["dec-w1-vicky-kimberly-final-pressure"],
      sortOrder: 57,
    },
    {
      slug: "dec-w3-tomas-vicky-objective-review",
      objectiveSlug: "company-month-dec-renew",
      accountSlug: null,
      title: "Revisar los objetivos de Vicky",
      description: "Comparar los objetivos de Vicky contra el documento de septiembre.",
      month: "diciembre",
      weekLabel: "15–21 dic",
      weekStart: "2026-12-15",
      dueDate: null,
      focus: "revisión anual",
      accountableOwnerName: "Tomás",
      supportingOwnerNames: ["Vicky"],
      status: "planned",
      dependencySlugs: ["dec-w2-vicky-final-feedback-ones"],
      sortOrder: 58,
    },

    // Diciembre — 22–31 dic.
    {
      slug: "dec-w4-tomas-consolidation",
      objectiveSlug: "company-month-dec-renew",
      accountSlug: null,
      title: "Consolidar lo firmado sin abrir negociaciones nuevas",
      description: "Semana de consolidación: no abrir negociaciones nuevas.",
      month: "diciembre",
      weekLabel: "22–31 dic",
      weekStart: "2026-12-22",
      dueDate: null,
      focus: "cierre anual",
      accountableOwnerName: "Tomás",
      supportingOwnerNames: ["Vicky"],
      status: "planned",
      dependencySlugs: ["dec-w3-vicky-kimberly-deadline"],
      sortOrder: 59,
    },
    {
      slug: "dec-w4-tomas-2027-final-and-january",
      objectiveSlug: "company-2027-opportunities",
      accountSlug: null,
      title: "Cerrar oportunidades 2027 y agendar enero",
      description: "Dejar al menos tres propuestas con presupuesto y fecha de decisión, y la primera reunión de enero en calendario.",
      month: "diciembre",
      weekLabel: "22–31 dic",
      weekStart: "2026-12-22",
      dueDate: "2026-12-23",
      focus: "planificación 2027",
      accountableOwnerName: "Tomás",
      supportingOwnerNames: [],
      status: "planned",
      dependencySlugs: ["nov-w4-tomas-2027-draft-complete"],
      sortOrder: 60,
    },
  ],
};

/**
 * The closing plan is owned by the two partners. Team members can execute
 * actions, but they must not appear as owners of the strategic objectives.
 * Acha is the only exception: her objectives are the operational work Vicky
 * cascades to her.
 */
export const OBJECTIVE_OWNER_REMAP: Record<string, "Tomás" | "Vicky" | "Acha"> = {
  Sil: "Tomás",
  Santi: "Tomás",
  Pau: "Tomás",
  PMs: "Vicky",
};

export const OBJECTIVE_PLAN_2026: ObjectivePlan2026 = {
  ...RAW_OBJECTIVE_PLAN_2026,
  objectives: RAW_OBJECTIVE_PLAN_2026.objectives.map((objective) => ({
    ...objective,
    ownerName: OBJECTIVE_OWNER_REMAP[objective.ownerName] ?? objective.ownerName,
  })),
};
